DROP DATABASE IF EXISTS pf_02;
CREATE DATABASE IF NOT EXISTS pf_02;
USE pf_02;

CREATE TABLE IF NOT EXISTS dados (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome_pista VARCHAR(255) NOT NULL,
    nome_equipe VARCHAR(255) NOT NULL,
    total_voltas INT NOT NULL,
    tempo_ultima_volta TIME NOT NULL,
    velocidade_media TIME NOT NULL,
    posicao INT NOT NULL
);